nathonius/obsidian-github-link

src/query/output.ts
src/util.ts

Will attempt to parse a string as json object notation to get nested properties
closes #8

✨ feat: 8 Add support for nested column props

---

.better-commits.json
package-lock.json
src/github/response.ts
src/github/url-parse.ts
src/icon.ts
src/inline/inline.ts
src/query/column/base.ts
src/query/column/issue.ts
src/query/column/pull-request.ts
src/query/column/repo.ts
src/query/output.ts
src/util.ts
styles.css

Columns will automatically link, set text, add icons, etc.
Closes: #11

✨ feat: #11 Add predefined PR table columns

---

package-lock.json
package.json
src/github/api.ts
src/github/cache.ts
src/github/github.ts
src/github/response.ts
src/icon.ts
src/query/column/base.ts
src/query/column/issue.ts
src/query/column/pull-request.ts
src/query/params.ts
src/query/processor.ts

✨ feat: #17 Add special issue columns

---

.github/workflows/release.yml

Drafts a new release when a tag is pushed
Closes: #31

🤖 ci: #31 Add release workflow

---

.github/workflows/build.yml
.github/workflows/code-check.yml
.github/workflows/release.yml
.prettierrc
package-lock.json
package.json

🤖 ci: #33 Add build and code check workflows

---

src/query/column/defaults.ts
src/query/output.ts

Not configurable for the moment, that can come later.
Closes: #28

✨ feat: #28 Add default columns for simple queries

---

src/github/api.ts
src/plugin.ts
src/query/column/issue.ts
src/query/processor.ts
src/settings.ts
src/util.ts

Setting will be added in a later PR.
Closes: #38

✨ feat: #38 Add logger with configurable log levels

---

README.md
manifest.json
package.json

📚 docs: #40 Remove some overly technical language from docs

---

.github/workflows/build.yml
.github/workflows/code-check.yml
.github/workflows/release.yml

🤖 ci: #43 Repair release action by uploading artifact

---

src/inline/inline.ts
src/inline/view-plugin.ts

🐛 fix: #48 Inline tags not rendered for links with display text

---

src/query/output.ts
styles.css

🐛 fix: #50 Tables horizontally scroll

---

src/github/github.ts
src/query/params.ts
src/query/processor.ts

🐛 fix: #16 Use org from params or query if possible

---

CHANGELOG.md
src/github/api.ts
src/github/github.ts
src/query/params.ts
src/query/processor.ts
src/settings.ts
src/util.ts

✨ feat: #24 Allow configuring default page size

---

README.md

📚 docs: #58 Add sonar badge to readme

---

src/github/api.ts
src/github/github.ts
src/github/response.ts
src/icon.ts
src/inline/inline.ts
src/plugin.ts
src/query/column/issue.ts
src/query/processor.ts

✨ feat: #70 Use specific icons for each state of issue and PR

---

src/icon.ts
styles.css

🐛 fix: #71 Correct closed as wont do issue icon color

---

src/icon.ts
src/settings.ts

✨ feat: #73 Add option for tooltip on issue and pr status

---

package-lock.json
package.json
src/github/api.ts
src/github/cache.ts
src/github/github.ts
src/inline/inline.ts
src/inline/view-plugin.ts
src/plugin.ts
src/query/column/issue.ts
src/util.ts

- 🐛 fix: #21 correct issue caching logic
- ✨ feat: #21 Lazy load tag content
- 🐛 fix: #21 correct pull request cache logic
- ✨ feat: #21 add request queue

Mitigate some rate limit issues

---

src/github/api.ts
src/github/github.ts
src/github/url-parse.ts
src/logger.ts
src/plugin.ts
src/settings.ts
src/util.ts

- 🔨 refactor: #61 Make logger and plugin settings constants
- 🔨 refactor: #61 Reduce complexity of url parse function

resolve sonar issues

---

src/query/output.ts
src/query/processor.ts
styles.css

Only applies for custom queries
Closes: #54

✨ feat: #54 Add link to query search on github

---

CONTRIBUTING.md

📚 docs: #46 Add CONTRIBUTING.md

---

src/inline/inline.ts
src/util.ts

✨ feat: #80 Show user or org name when transforming link to repo

---

src/github/api.ts
src/github/github.ts
src/github/response.ts
src/icon.ts
src/inline/inline.ts
src/plugin.ts
src/settings.ts
styles.css

Can be more granular in the future
Closes: #72

✨ feat: #72 Add simple PR check status icons

---

src/plugin.ts

Untested but this probably fixes it

fix: #104 init data to empty object

---

package-lock.json
package.json
src/github/api.ts
src/inline/inline.ts
styles.css

- **✨ feat: #85 Add error icon to tags that could not be retrieved**
- **🔨 refactor: #85 Move queue to dependencies**

Show errored tags with some info

---

.github/workflows/code-check.yml
.gitignore
__mocks__/obsidian.ts
__mocks__/obsidian/App.ts
__mocks__/obsidian/Modal.ts
__mocks__/obsidian/Plugin.ts
__mocks__/obsidian/PluginSettingTab.ts
__mocks__/queue.ts
eslint.config.mjs
jest.config.mjs
package-lock.json
package.json
src/plugin.spec.ts
src/settings/types.ts
tsconfig.json

- **🚨 test: #107 Set up jest**
- **🚨 test: #107 Working simple test**
- **🚨 test: #107 Add some general sanity tests for the setting up the plugin**
- **🤖 ci: #107 Add test to code check workflow**

Unit tests

---

src/inline/inline.ts
src/query/column/base.ts
src/query/output.ts

Also added the actual url to an authors page when rendering it in the table.
Closes: #115

🐛 fix: #115 Ensure popout windows arent closed when clicking links

---

src/query/column/base.ts
styles.css

✨ feat: #119 Add Labels column

---

src/github/response.ts
src/query/column/base.ts

✨ feat: #123 Add assignee column

---

src/plugin.spec.ts
src/plugin.ts
src/query/query.ts
src/settings/settings-tab.ts
src/settings/types.ts

✨ feat: #126 Add toggle for external link

---

src/github/api.ts
src/github/github.ts
src/query/query.ts
tsconfig.json

✨ feat: #114 Support org issues query

---

package-lock.json
package.json
src/inline/view-plugin.ts

🐛 fix: #121 Rewrite live preview renderer

---

src/inline/view-plugin.ts

🐛 fix: #139 Adjust url regex to exclude URLs with display text

---

src/settings/account.ts

🐛 fix: #143 Use custom oauth setting during token gen for new account

---

src/settings/account.ts

Was resulting in 404
Closes: #142

🐛 fix: #142 Trim oauth client id of whitespace

---

src/settings/settings-tab.ts
styles.css

✨ feat: #154 Add manual inputs for all slider settings

---

src/inline/inline.ts
styles.css

✨ feat: #158 Always display issue number
